### ISSUE TITLE
Traceback error whenever i click save

### ISSUE THREAD

**Issue by AcidRain999** [morpheus65535/oscarr#10]
i can get oscarr running and i can browse to its frontend but when i edit settings and click save, it will shoot an error like this one:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python3.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "oscarr.py", line 406, in save_settings
    after = (unicode(settings_general_ip), int(settings_general_port), unicode(settings_general_baseurl))
NameError: name 'unicode' is not defined

i have restarted the server and program and still same error, any help is appreciated

**Comment by morpheus65535** [comment]
Python 3 is unsupported.
