### ISSUE TITLE
Unable to determine the name of the local timezone

### ISSUE THREAD

**Issue by Mizio66** [morpheus65535/oscarr#13]
Running it i have this error...

Traceback (most recent call last):
  File "oscarr.py", line 73, in <module>
    from scheduler import *
  File "/volume2/GitProjects/oscarr/scheduler.py", line 8, in <module>
    scheduler.add_job(check_and_apply_update, 'interval', hours=6, max_instances=1, coalesce=True, misfire_grace_time=15, id='update_oscarr', name='Updat                                     e oscarr from source on Github')
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 420, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 921, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 906, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/lib/python2.7/site-packages/apscheduler/triggers/interval.py", line 38, in __init__
    self.timezone = astimezone(timezone)
  File "/usr/lib/python2.7/site-packages/apscheduler/util.py", line 96, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using t                                     imezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).

**Comment by morpheus65535** [comment]
Make sure you've defined your timezone in Linux.
