### ISSUE TITLE
Saving plex settings

### ISSUE THREAD

**Issue by HPloco** [morpheus65535/oscarr#14]
Installed in a custom jail on freenas 11.3. If i try to save any settings i'm redirected to a 500 page:

Error: 500 Internal Server Error
Sorry, the requested URL 'http://192.168.1.170:5656/save_settings' caused an error:

Internal Server Error
Exception:
NameError("name 'unicode' is not defined")
Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "oscarr.py", line 406, in save_settings
    after = (unicode(settings_general_ip), int(settings_general_port), unicode(settings_general_baseurl))
NameError: name 'unicode' is not defined

**Comment by morpheus65535** [comment]
Oscarr is untested with Python 3.x and will probably not work.
