### ISSUE TITLE
Sonarr + Bazarr connect issue

### ISSUE THREAD

**Issue by DarkAllMan** [morpheus65535/oscarr#3]
I'm unable to connect to Sonarr/Bazarr.
Sonarr error:
`AttributeError("'NoneType' object has no attribute 'append'",)`

`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "C:\Oscarr\oscarr\oscarr.py", line 232, in sonarr
    rootfolder_list.append([rootfolder['path'], sizeof_fmt(rootfolder['freeSpace']), sizeof_fmt(rootfolder['totalSpace']), int(percent)])
AttributeError: 'NoneType' object has no attribute 'append'`

Bazarrerror:
`SyntaxError('EOL while scanning string literal', ('<unknown>', 1, 10, "['en', 'nl"))`

`Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "C:\Python27\lib\site-packages\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "C:\Oscarr\oscarr\oscarr.py", line 365, in bazarr
    output = template('bazarr', __file__=__file__, oscarr_version=oscarr_version, base_url=base_url, missing_list=missing_list, history_list=history_list)
  File "C:\Python27\lib\site-packages\bottle.py", line 3622, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\Python27\lib\site-packages\bottle.py", line 3411, in render
    self.execute(stdout, env)
  File "C:\Python27\lib\site-packages\bottle.py", line 3398, in execute
    eval(self.co, env)
  File "C:\Oscarr\oscarr\views\bazarr.tpl", line 89, in <module>
    subs_languages = ast.literal_eval(str(row[3]))
  File "C:\Python27\lib\ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Python27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    ['en', 'nl
             ^
SyntaxError: EOL while scanning string literal`

**Comment by morpheus65535** [comment]
What version of Sonarr are you using?

**Comment by DarkAllMan** [comment]
Sonarr Ver. 2.0.0.5252

**Comment by TheFes** [comment]
I have the same issue with Bazarr
I do use a base url here, which is "/bazarr/"
And I have a password set.

In the Bazarr settings there is no option to set API key or password, could this cause the issue?

**Comment by TheFes** [comment]
Something changed on my side, it works now.
Only change I made myself is that I forgot to add a / at the end of the Oscarr base url. For that reason my reverse proxy setup did not work. So I added a / for that reason.
I don't know if there was an update at your side, or that this was the cause for my error, but the Bazarr integration in Oscarr does work now.

**Comment by edualm** [comment]
Hijacking this issue since I have the same issue, but with bazarr.

The error is similar:

```
Exception:

SyntaxError('EOL while scanning string literal', ('<unknown>', 1, 10, "['en', 'pb"))
```

I'm running Bazarr Ver. 0.8.4.3.

Please let me know if I can help with any logs.

**Comment by morpheus65535** [comment]
> Hijacking this issue since I have the same issue, but with bazarr.
> 
> The error is similar:
> 
> ```
> Exception:
> 
> SyntaxError('EOL while scanning string literal', ('<unknown>', 1, 10, "['en', 'pb"))
> ```
> 
> I'm running Bazarr Ver. 0.8.4.3.
> 
> Please let me know if I can help with any logs.

Update to 0.8.4.4

**Comment by edualm** [comment]
@morpheus65535 Done, same error.

**Comment by morpheus65535** [comment]
> @morpheus65535 Done, same error.

Open an issue on Bazarr Github.

**Comment by edualm** [comment]
Done. https://github.com/morpheus65535/bazarr/issues/1030
