### ISSUE TITLE
Internal Server Error while connecting to Plex

### ISSUE THREAD

**Issue by Tr4il** [morpheus65535/oscarr#5]
I configured oscarr to connect to my Plex server, and it is finding that but I'm getting an internal server error:

Exception
`KeyError('index',)`

Traceback:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/oscarr/oscarr.py", line 168, in plex
    series_list.append([True if 'viewCount' in series else False, series['grandparentTitle'], series['title'], series['parentIndex'], series['index'], datetime.fromtimestamp(series['addedAt']).strftime('%Y-%m-%d')])
KeyError: 'index'`

Any solution?

**Comment by sambarlick** [comment]
I'm getting this same issue, did you ever solve it?
