### ISSUE TITLE
sonarr+oscarr error loading

### ISSUE THREAD

**Issue by pkishino** [morpheus65535/oscarr#8]
latest oscarr version in docker,
sonarr: 2.0.0.5338
after adding sonarr config and clicking sonarr icon:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/oscarr/oscarr.py", line 255, in sonarr
    if 'statistics' in item['seasons'][-1]:
IndexError: list index out of range
```
in docker log.
browser shows  500 ISE

**Comment by pkishino** [comment]
so, this happens for sonarr entries with no seasons added..added workaround, update oscarr.py lines 255 and 271 and add ` item['seasons'] and ` into the if statement

**Comment by pkishino** [comment]
will add PR later

**Comment by morpheus65535** [comment]
Thanks!
